dev-nifi:
  nifi_url: https://194.163.178.140:7443/nifi-api
  registry_url: http://194.163.178.140:18080/nifi-registry-api
  nifi_user: admin
  nifi_pass: '123456789012'
  nifi_verify_ssl: false
  suppress_ssl_warnings: true
  # nifi_auth_method: basic 
  registry_auth_method: unauthenticated

uat-nifi:
  nifi_url: https://194.163.178.140:7443/nifi-api
  registry_url: http://194.163.178.140:18080/nifi-registry-api
  nifi_user: admin
  nifi_pass: '123456789012'
  nifi_verify_ssl: false
  suppress_ssl_warnings: true
  # nifi_auth_method: basic
  registry_auth_method: unauthenticated
